services:
  - type: web
    name: rsgms
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: rsgms-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: rsgms-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: rsgms-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: rsgms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rsgms-db
          property: password

databases:
  - name: rsgms-db
    databaseName: rsgms_db
    plan: free
